# Generated by Django 4.1.7 on 2023-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('emalil', models.EmailField(max_length=254)),
                ('input_time', models.IntegerField()),
                ('source', models.CharField(choices=[('misp', 'MISP'), ('zoneh', 'ZoneH')], max_length=10)),
            ],
        ),
    ]
