# Generated by Django 4.1.7 on 2023-04-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='source',
        ),
    ]
