# Generated by Django 4.1.7 on 2023-04-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_remove_user_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
