# Generated by Django 4.1.7 on 2023-04-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
