# Generated by Django 4.1.7 on 2023-04-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0007_addlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddLink',
        ),
    ]
